[versions]
compose-plugin = "1.8.1"
kotlin = "2.2.21"
napier = "2.7.1"
theme-detector = "3.9.1"
dokka = "2.1.0"
publish = "0.32.0"
collections = "0.4.0"

[libraries]
aakira-napier = { module = "io.github.aakira:napier", version.ref = "napier" }
themedetector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "theme-detector" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
kotlinx-Collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "collections" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }